# Generated by Django 4.2.2 on 2023-07-06 16:06

import ckeditor.fields
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('sdescription', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=500)),
                ('eemail', models.CharField(max_length=500)),
                ('expire_in_days', models.CharField(default='30', max_length=500)),
                ('time', models.FloatField(default=time.time, editable=False)),
                ('posted_by', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('comapny', models.CharField(max_length=500)),
                ('job', models.CharField(max_length=500)),
                ('email_verfied', models.BooleanField(default=False)),
                ('subscriber', models.BooleanField(default=False)),
                ('key', models.BooleanField(default=False)),
                ('img_url', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
