# Generated by Django 4.2.2 on 2023-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='key',
            field=models.CharField(max_length=500),
        ),
    ]
