# Generated by Django 4.2.2 on 2023-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_profiles_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='background_img_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='logo_img_url',
            field=models.CharField(default="{% static 'assets/img/joblogo.png' %}", max_length=500),
            preserve_default=False,
        ),
    ]
