# Generated by Django 4.2.2 on 2023-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_jobs_background_img_url_jobs_logo_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expire_in_days',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='time',
            field=models.DateField(editable=False),
        ),
    ]
