# Generated by Django 4.2.2 on 2023-07-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_jobs_category_alter_jobs_expire_in_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='category',
            new_name='company',
        ),
    ]
