# Generated by Django 4.2.2 on 2023-07-09 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_category_jobs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='subscriber_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 8, 33, 8, 18215), editable=False),
        ),
    ]
