# Generated by Django 4.1.7 on 2023-07-29 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_profiles_subscriber_id_alter_jobs_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='comapny',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='time',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='img_url',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg', max_length=500),
        ),
    ]
